version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    restart: always
    networks:
      - ollama-net 
    volumes:
    - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
  
  local_deep_researcher:
    container_name: local_deep_researcher
    build: .
    ports:
      - "2024:2024"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434 
    depends_on:
      - ollama
    networks:
      - ollama-net

networks:
  ollama-net:
    driver: bridge

volumes:
  ollama: